"""Installed libraries: the ``lib/`` staging tree and the loader (D57).

A library is never run, so it gets none of the shim system (D11/D38). What it
gets instead is a version-less path a sourcing script can name:

    ~/.scripticus/lib/scr_load.sh        the loader itself
    ~/.scripticus/lib/<namespace>/<name>/load.sh

The second is a *generated wrapper*, the sourcing counterpart of the D11 exec
shims: two lines that point `SCR_LIB_DIR` at the real versioned tree under
``pkgs/`` and dot-source its entry point. Wrapping rather than symlinking keeps
the path version-less without needing symlink privileges (bash-on-Windows is a
supported target), and makes an upgrade a rewrite of one small file — exactly
how the exec shims already behave.

Nothing here records ownership: a library is referenced by its full
``namespace/name``, so two libraries can never contend for a name and there is
no last-install-wins to arbitrate.
"""

import shutil
from importlib import resources
from pathlib import Path

LOADER_NAME = "scr_load.sh"

# The wrapper is always `load.sh` whatever the library's language: `sh` and
# `bash` share an extension, and the dialect is the package's declared language
# rather than anything the filename says.
WRAPPER_NAME = "load.sh"


def loader_text() -> str:
    """The loader script, shipped as package data beside this module."""
    return (
        resources.files("scripticus.loader").joinpath(LOADER_NAME).read_text()
    )


def lib_root(home: Path) -> Path:
    return home / "lib"


def loader_path(home: Path) -> Path:
    return lib_root(home) / LOADER_NAME


def library_dir(home: Path, namespace: str, name: str) -> Path:
    return lib_root(home) / namespace / name


def install_loader(home: Path) -> Path:
    """Write (or refresh) the loader. Called by `init` and by every library
    install, so a tree whose loader predates an upgrade heals itself.
    """
    path = loader_path(home)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(loader_text())
    return path


def _sh_quote(value: str) -> str:
    """Escape a path for a double-quoted shell string."""
    for character in ("\\", '"', "$", "`"):
        value = value.replace(character, f"\\{character}")
    return value


def wrapper_text(install_dir: Path, entrypoint: str) -> str:
    """The generated ``load.sh`` that points at one installed library tree.

    ``SCR_LIB_DIR`` is set before sourcing so the library can reach its own
    siblings (``. "$SCR_LIB_DIR/src/helpers.sh"``), which POSIX sh otherwise
    gives a sourced file no way to find. ``scr_load`` restores the caller's
    value afterwards, so a library that loads another library is unaffected.
    """
    directory = _sh_quote(str(install_dir))
    return (
        "# Generated by scripticus — do not edit; reinstalling regenerates it.\n"
        f'SCR_LIB_DIR="{directory}"\n'
        f'. "$SCR_LIB_DIR/{entrypoint}"\n'
    )


def stage_library(
    home: Path, namespace: str, name: str, install_dir: Path, entrypoint: str
) -> Path:
    """Point ``lib/<namespace>/<name>/load.sh`` at an installed library tree."""
    install_loader(home)
    directory = library_dir(home, namespace, name)
    directory.mkdir(parents=True, exist_ok=True)
    wrapper = directory / WRAPPER_NAME
    wrapper.write_text(wrapper_text(install_dir, entrypoint))
    return wrapper


def remove_library(home: Path, namespace: str, name: str) -> None:
    """Drop a library's staged directory, pruning the namespace level when it
    empties. Safe to call for a package that never was a library.
    """
    directory = library_dir(home, namespace, name)
    shutil.rmtree(directory, ignore_errors=True)
    parent = directory.parent
    if parent.is_dir() and parent != lib_root(home) and not any(parent.iterdir()):
        parent.rmdir()


def orphaned_libraries(lock: dict) -> list[dict]:
    """Installed libraries nothing left in the lockfile depends on.

    Only packages that arrived as dependencies qualify: one the user installed
    directly was asked for, and stays until it is unasked for. The answer is an
    *advisory* — uninstall never removes a package the user did not name (D57),
    which keeps it consistent with orphaned command packages, which are also
    left alone.
    """
    needed = {
        target
        for entry in lock["packages"]
        for target in entry.get("dependencies", {})
    }
    return [
        entry
        for entry in lock["packages"]
        if entry.get("library")
        and not entry.get("direct")
        and f"{entry['namespace']}/{entry['name']}" not in needed
    ]
